export enum DomainArea {
  AFFILIATE = 'AFFILIATE',

  CATALOG = 'CATALOG',

  CONTACTS = 'CONTACTS',

  REMINDERS = 'REMINDERS',

  PROFILE = 'PROFILE',

  BILLING = 'BILLING',

  CREDIT_CARD = 'CREDIT_CARD',

  CREDIT = 'CREDIT',

  CONFIGURATION_RECEIVABLES = 'CONFIGURATION_RECEIVABLES',

  CONFIGURATION_PAYABLES = 'CONFIGURATION_PAYABLES',

  ORDER_CONFIMRATIONS = 'ORDER_CONFIMRATIONS',

  COSTS = 'COSTS',

  CATEGORIES_PAYABLES = 'CATEGORIES_PAYABLES',

  COST_UNITS = 'COST_UNITS',

  EFFORTS = 'EFFORTS',

  EXPENSES = 'EXPENSES',

  EXPORTS = 'EXPORTS',

  INVOICES = 'INVOICES',

  LETTERS = 'LETTERS',

  NEWSLETTERS = 'NEWSLETTERS',

  NOTIFICATIONS = 'NOTIFICATIONS',

  OFFERS = 'OFFERS',

  PROJECTS = 'PROJECTS',

  DELIVERY_NOTES = 'DELIVERY_NOTES',

  ACTIVITES = 'ACTIVITES',

  CONFIGURATION_PROJECT_TIME = 'CONFIGURATION_PROJECT_TIME',

  RIGHTS = 'RIGHTS',

  MAILING_CENTER = 'MAILING_CENTER',

  TIME_REPORTING = 'TIME_REPORTING',

  UNITS = 'UNITS',

  USERS = 'USERS',
}
